version: "3.9"

services:
  db:
    image: postgres:13
    container_name: django_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    build: .
    restart: always
    command: tail -f /dev/null
    container_name: django_web
    volumes:
      - .:/test-drf
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
  redis:
    container_name: django_redis
    image: redis
  celery:
    container_name: django_celery
    restart: always
    build:
      context: .
    volumes:
      - .:/test-drf
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
      - web

volumes:
  postgres_data:

