# Generated by Django 4.1.2 on 2022-12-12 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technology',
            options={'verbose_name': 'Technology', 'verbose_name_plural': 'Technologies'},
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='technology',
            new_name='technologies',
        ),
    ]
